name: Appian CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Archive Appian Package
        run: mv environment-cleanup-app-2.1.1.zip deploy-package.zip

      - name: Upload Artifact for Deployment
        uses: actions/upload-artifact@v4
        with:
          name: appian-package
          path: environment-cleanup-app-2.1.1.zip
